### ISSUE TITLE
New Hook

### ISSUE THREAD

**Issue by 0xaaiden** [fewwwww/awesome-uniswap-hooks#42]
Title: Attestation Hook
Description: This hook allows for the querying of attestations from various attestation protocols. Check returned responses against preset criteria in any of the hook functions.
Creator: CliqueOfficial
Website: https://www.clique.social/discover/attestor
Github Repository: https://github.com/CliqueOfficial/attestation-hooks

**Comment by fewwwww** [comment]
Thank you!
